server:
  port: 5001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5002/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000

  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true